### ISSUE TITLE
max_two_step incorrect

### ISSUE THREAD

**Issue by TheFirstAvenger** [parkerl/ecto_query_library#4]
I ran into an issue while reading this:

https://elixirnation.io/references/ecto-query-examples#max_two_step

which seems to come from here:

https://github.com/parkerl/ecto_query_library#max_two_step

and outlined it here:

https://gist.github.com/TheFirstAvenger/6eaeda85c89d7d530647

It looks like the actual code is updated to resolve the issue here:

https://github.com/parkerl/ecto_query_library/blob/master/lib/fishing_spot/queries.ex#L163-L175

but the fix isn't applied to the readme or the first link (not sure if that is yours or a static copy someone made)

**Comment by parkerl** [comment]
@TheFirstAvenger Thanks so much for tracking all that down and alerting me! 

It looks like https://elixirnation.io/references/ecto-query-examples#max_two_step is puling my changes.

I will update to post. You rock.
